-- ============================================================
--  Streakproof — template library (generated by gen_seed.py)
--  Applied by `supabase db push`. Safe to re-run: every insert is an
--  upsert on the template slug, and user plans are never touched.
--
--  DO NOT EDIT BY HAND. Edit gen_seed.py and regenerate.
-- ============================================================

-- ---------- Bodyweight — anywhere, no kit ------------------------------
do $$
declare v_plan uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility)
  values (null, true, 'gym', 'bodyweight-anywhere', 'Bodyweight — anywhere, no kit', 'Three rotating days you can do in a hotel room, a garage or a living room. No equipment beyond a chair and a wall. Pulls are included, which most bodyweight plans skip.', 'template', 'public')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  -- Templates are regenerated wholesale; user plans are untouched.
  delete from days where plan_id = v_plan;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'A', 'Day A · Push', 'Chest, shoulders, triceps — floor only', 1)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Push-up (or incline push-up)', '3 × 8–15 · push', 'Hands under shoulders, body one line from ear to heel. Too hard? Put your hands on a counter or the arm of the sofa — that''s not cheating, it''s the same movement at a workable angle.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Pike Push-up', '3 × 6–10 · push', 'Hips high, head between your hands like an upside-down V. Lower the crown of your head toward the floor. This is the closest thing to an overhead press without a weight.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Bench/Chair Dip', '3 × 8–12 · push', 'Hands on a chair edge behind you, legs out in front. Lower until your upper arms are parallel to the floor. Stop if it pinches the front of your shoulder — walk your feet in instead.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Wall Sit', '3 × 30–45 sec · legs', 'Back flat to the wall, thighs parallel to the floor, knees over ankles. It''s meant to burn. Breathe through it.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Hollow Hold', '3 × 20–30 sec · core', 'Lie on your back, press your lower back into the floor, lift shoulders and legs. If your back arches, raise your legs higher until it doesn''t.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: 10 min brisk walk', 'finisher · conditioning', 'Outside if you can. This is for the mood, not the calories.', 1, 45, 60, true, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'B', 'Day B · Pull & legs', 'Back, hamstrings, glutes', 2)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Doorway/Table Row', '3 × 8–12 · pull', 'Lie under a sturdy table and pull your chest to the edge, or hold a doorframe and lean back with straight arms. Squeeze the shoulder blades together at the top.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Bulgarian Split Squat', '3 × 8–10 each · legs', 'Back foot on a chair, front foot far enough forward that your knee stays over your ankle. Down slow, up strong. Brutal without any weight at all.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Glute Bridge', '3 × 12–15 · hinge', 'On your back, heels close to your bum, drive hips up and squeeze at the top for a second. Ribs down — don''t arch your lower back to get higher.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Single-leg Calf Raise', '3 × 12–15 each · legs', 'Hold a wall for balance. Full range: heel all the way down, all the way up. Slow on the way down.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Superman Hold', '3 × 20–30 sec · core', 'Face down, lift chest and thighs off the floor. Look at the floor, not forward — keep your neck neutral.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: stretch, 5 min', 'finisher · conditioning', 'Hamstrings, hip flexors, chest. Not optional if you sit all day, but marked optional so a rushed day still counts.', 1, 45, 60, true, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'C', 'Day C · Full body', 'Everything, moving quickly', 3)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Squat', '3 × 15–20 · legs', 'Feet shoulder-width, sit down and back, chest up. High reps here — this is conditioning as much as strength.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Push-up', '3 × 8–15 · push', 'Same as Day A. If Day A''s felt easy, slow the lowering phase to three seconds.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Reverse Lunge', '3 × 10 each · legs', 'Step back, not forward — much kinder on the knees. Front shin stays vertical.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Doorway/Table Row', '3 × 8–12 · pull', 'Pulling twice a week is the point; most bodyweight plans skip it entirely and people end up rounded forward.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Dead Bug', '3 × 10 each · core', 'On your back, opposite arm and leg extend while your lower back stays glued to the floor. Slow. If your back lifts, shorten the range.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: 10 min cardio', 'finisher · conditioning', 'Stairs, a walk, skipping, anything. Easy effort.', 1, 45, 60, true, 6 from d;

  perform public.refresh_plan_estimates(v_plan);
end $$;

-- ---------- Lean Down — 3 days, full body ------------------------------
do $$
declare v_plan uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility)
  values (null, true, 'gym', 'fat-loss-full-body', 'Lean Down — 3 days, full body', 'Three full-body days with short rests and a conditioning finisher on each. Built for losing weight without living in the gym: compound lifts first, intervals last, nothing longer than an hour.', 'template', 'public')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  -- Templates are regenerated wholesale; user plans are untouched.
  delete from days where plan_id = v_plan;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'A', 'Day A · Lower + carry', 'Big movements, short rests', 1)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Goblet Squat', '3 × 10–12 · legs', 'Hold one dumbbell at your chest like a goblet. Elbows inside your knees at the bottom. Easier to keep upright than a back squat, which is why it''s here.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Dumbbell Romanian Deadlift', '3 × 10–12 · hinge', 'Push your hips back, dumbbells sliding down your thighs. Stop when you feel the hamstring stretch — going lower just rounds your back.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Walking Lunge', '3 × 12 each · legs', 'Long strides. If your balance is shaky, do reverse lunges in place instead.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Farmer''s Carry', '3 × 40 m · core', 'Heaviest dumbbells you can hold with a straight back. Walk. This is core work that doesn''t feel like core work, and it burns more than it looks.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Incline Walk', '12 min · conditioning', 'Treadmill at a real incline, or a hill. Brisk but conversational — this is not a sprint session and it is not meant to wreck you.', 1, 60, 60, false, 5 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'B', 'Day B · Upper + intervals', 'Push, pull, then bike', 2)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Dumbbell Bench Press', '3 × 8–12 · push', 'Shoulder blades pinched back into the bench. Elbows about 45 degrees from your body, not flared straight out.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Seated Cable Row', '3 × 10–12 · pull', 'Chest tall, pull to your belly button, squeeze for a beat. Don''t rock backwards to move more weight.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Dumbbell Shoulder Press', '3 × 10–12 · push', 'Seated with back support. Press up, don''t lean back to turn it into an incline press.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Lat Pulldown', '3 × 10–12 · pull', 'Drive elbows down toward your hips. Wide grip, no swinging.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Bike Intervals', '8 × 30 sec hard / 90 sec easy · conditioning', 'Hard means you couldn''t hold a conversation. Easy means you fully recover. If you can''t finish all eight, you went too hard on the first two.', 6, 45, 60, false, 5 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'C', 'Day C · Circuit', 'Three rounds, minimal rest', 3)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Kettlebell/Dumbbell Swing', '3 × 15 · hinge', 'Hips snap forward, the weight floats — it''s a hinge, not a squat, and definitely not a front raise. Arms are rope.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Push-up', '3 × 10–15 · push', 'Hands on a bench if the floor is too much today. Keep moving.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Dumbbell Row', '3 × 12 each · pull', 'One hand on a bench, pull the dumbbell to your hip. Don''t twist your torso to help.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Step-up', '3 × 12 each · legs', 'Onto a bench about knee height. Push through the top foot, don''t hop off the bottom one.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Plank', '3 × 30–45 sec · core', 'Straight line, glutes tight. Rest 30 seconds between rounds and go again.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: 10 min walk', 'finisher · conditioning', 'Cool down and let your heart rate come back to earth.', 1, 45, 60, true, 6 from d;

  perform public.refresh_plan_estimates(v_plan);
end $$;

-- ---------- Push / Pull / Legs — build muscle ------------------------------
do $$
declare v_plan uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility)
  values (null, true, 'gym', 'push-pull-legs-muscle', 'Push / Pull / Legs — build muscle', 'The classic hypertrophy split, run three or six days a week. Higher volume per muscle than the full-body plans. Needs a proper gym with barbells, cables and machines.', 'template', 'public')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  -- Templates are regenerated wholesale; user plans are untouched.
  delete from days where plan_id = v_plan;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'A', 'Day A · Push', 'Chest, shoulders, triceps', 1)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Barbell Bench Press', '4 × 6–8 · push', 'Feet planted, shoulder blades retracted. Bar to mid-chest, elbows tucked to about 45 degrees. Have a spotter or use the safety pins.', 4, 45, 150, false, 1 from d
    union all
    select id, 'Incline Dumbbell Press', '3 × 8–12 · push', 'Bench at 30 degrees. Higher than that and it becomes a shoulder press.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Overhead Press', '3 × 6–10 · push', 'Standing, squeeze your glutes so you don''t lean back. Bar path goes past your face, not around it.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Cable Fly', '3 × 12–15 · push', 'Slight bend in the elbows, held constant. Think about hugging a barrel. Squeeze at the middle.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Triceps Rope Pushdown', '3 × 12–15 · push', 'Elbows pinned to your sides. Only the forearms move. Spread the rope at the bottom.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Lateral Raise', '3 × 15–20 · push', 'Light. Lead with the elbows, stop at shoulder height. This is the one that actually makes shoulders look wider.', 3, 45, 90, false, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'B', 'Day B · Pull', 'Back, rear delts, biceps', 2)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Pull-up or Lat Pulldown', '4 × 6–10 · pull', 'Full hang at the bottom, chin over the bar at the top. Use the assisted machine or a band rather than doing half reps.', 4, 45, 150, false, 1 from d
    union all
    select id, 'Barbell Row', '4 × 8–10 · pull', 'Torso about 45 degrees, pull to your belly button. If you''re jerking the weight up with your lower back, it''s too heavy.', 4, 45, 150, false, 2 from d
    union all
    select id, 'Seated Cable Row', '3 × 10–12 · pull', 'Chest proud, shoulder blades squeezing together at the end of each rep.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Face Pull', '3 × 15–20 · pull', 'Rope to your forehead, elbows high, externally rotate at the end. This is the single best insurance policy for shoulders that bench a lot.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Dumbbell Curl', '3 × 10–12 · pull', 'No swinging. If your elbows drift forward, the weight''s too heavy.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Hammer Curl', '3 × 10–12 · pull', 'Neutral grip, thumbs up. Hits the forearm and the part of the biceps that adds thickness.', 3, 45, 90, false, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'C', 'Day C · Legs', 'Quads, hamstrings, glutes, calves', 3)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Barbell Back Squat', '4 × 6–8 · legs', 'Brace hard, sit down and back, at least parallel. This is the one exercise worth being fussy about form on.', 4, 45, 150, false, 1 from d
    union all
    select id, 'Romanian Deadlift', '3 × 8–10 · hinge', 'Hips back, flat back, bar close. Feel it in the hamstrings, not the lower back.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Leg Press', '3 × 10–12 · legs', 'Don''t lock out hard at the top and don''t let your lower back round off the pad at the bottom.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Leg Curl', '3 × 12–15 · legs', 'Slow on the way back. Hamstrings respond well to the lowering half.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Walking Lunge', '3 × 10 each · legs', 'Long strides, upright torso.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Standing Calf Raise', '4 × 12–15 · legs', 'Full stretch at the bottom, pause at the top. Calves need the range, not the weight.', 4, 45, 90, false, 6 from d;

  perform public.refresh_plan_estimates(v_plan);
end $$;

