-- ============================================================
--  Streakproof — template library (generated by gen_seed.py)
--  Applied by `supabase db push` after the rls migration. Safe to re-run.
--
--  DO NOT EDIT BY HAND. Edit gen_seed.py and regenerate:
--      python3 supabase/tools/gen_seed.py > supabase/migrations/20260802000004_templates.sql
-- ============================================================

-- ---------- Full Body + Pool — 3-4 days ------------------------------
do $$
declare v_plan uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility)
  values (null, true, 'gym', 'full-body-pool', 'Full Body + Pool — 3-4 days', 'Three rotating full-body days (squat / hinge / athletic) plus a zero-impact pool day for bad knees, hot weeks, or the day before a game. Needs a full gym.', 'template', 'public')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  -- Templates are regenerated wholesale; user plans are untouched.
  delete from days where plan_id = v_plan;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'A', 'Day A · Squat', 'Full body — squat focus', 1)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Barbell Back Squat', '3 × 6–8 · legs', 'Bar on your traps, not your neck. Brace like someone''s about to poke your gut, sit down & back (knees track over toes), drive up through mid-foot. Go to at least parallel.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Dumbbell Bench Press', '3 × 8–10 · push', 'Slight arch, shoulder blades pinched back & down. Lower the dumbbells to chest level with elbows ~45°, press up and slightly together.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Lat Pulldown', '3 × 8–12 · pull', 'Chest tall, pull the bar to your collarbone by driving elbows down toward your hips. Don''t lean way back. Squeeze your back, don''t just yank with arms.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Leg Press', '3 × 10–12 · legs', 'Feet shoulder-width mid-platform. Lower until knees ~90°, keep lower back flat on the pad. Push through heels, don''t lock knees hard at the top.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Plank', '3 × 30–45 sec · core', 'Forearms down, body one straight line — no saggy hips, no piked butt. Squeeze glutes and abs. Breathe. Add time as it gets easy.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: 10 min cardio', 'finisher · conditioning', 'Easy-to-moderate. Bike, row, or incline walk. Purely for the energy/mood boost and recovery — don''t smoke yourself.', 1, 45, 60, true, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'B', 'Day B · Hinge', 'Full body — hinge focus', 2)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Romanian Deadlift (RDL)', '3 × 6–8 · hinge', 'Soft knees, push hips BACK (not down) like closing a car door with your butt. Bar slides down your thighs, feel the hamstring stretch, then drive hips forward to stand tall. Flat back the whole time.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Overhead Press (DB or barbell)', '3 × 8–10 · push', 'Brace core, squeeze glutes so you don''t lean back. Press straight up, biceps ending near ears. Don''t let it drift forward. If your lower back arches hard, lighten it.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Chest-Supported Row', '3 × 10–12 · pull', 'Chest on the pad. Row the weight to your lower ribs by pulling elbows back and squeezing shoulder blades together. Pause a beat at the top. Controlled on the way down.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Walking Lunges', '3 × 10/leg · legs', 'Long-ish step, drop the back knee toward the floor, torso upright. Push through the FRONT heel to stand. Great carryover to sprinting on the field.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Pallof Press', '3 × 10/side · core', 'Cable at chest height, stand side-on. Press the handle straight out and resist it pulling you toward the machine. Anti-rotation = a bulletproof core for twisting/throwing.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Optional: intervals', 'finisher · conditioning', '6–8 rounds: 20 sec hard (bike/row/assault), 40 sec easy. Big bang for fat loss and matches the stop-start of dodgeball.', 1, 45, 60, true, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'C', 'Day C · Athletic', 'Full body — athletic + conditioning', 3)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Trap-Bar Deadlift', '3 × 6–8 · hinge/legs', 'Stand inside the trap bar, hips between squat and RDL height, flat back, chest up. Push the floor away with your feet and stand tall. Easiest deadlift to learn — very knee/back friendly.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Incline Dumbbell Press', '3 × 8–10 · push', 'Bench at ~30°. Lower dumbbells to upper chest, elbows ~45°, press up. Hits the upper chest and shoulders — good for that athletic look.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Single-Arm Dumbbell Row', '3 × 10/arm · pull', 'One hand & knee on a bench, flat back. Row the dumbbell to your hip, elbow close to your side, squeeze at the top. Don''t twist your torso to cheat it up.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Face Pulls', '3 × 15 · pull/health', 'Rope at face height, pull toward your forehead with elbows high, thumbs going back. Bulletproofs your shoulders for all that overhead throwing. Light weight, high reps.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Farmer Carry', '3 × ~30 m · core/grip', 'Heavy dumbbell in each hand, stand tall, shoulders back, brace core, walk. Don''t lean. Builds a rock-solid trunk and crushing grip — pure athlete fuel.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Hanging Knee Raises', '3 × 10–15 · core', 'Hang from the bar, no swinging. Curl your knees up toward your chest using your abs (not momentum). Lower slow. Use an ab-strap station if grip gives out first.', 3, 45, 90, false, 6 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'P', 'Pool', 'Bodyweight only — low-impact conditioning', 4)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Warm-up swim / water walk', '5 min · warm-up', 'Easy laps of any stroke, or just walk/jog across the shallow end pushing through the water. Get your body temp up and shoulders loose before the harder stuff.', 1, 60, 60, false, 1 from d
    union all
    select id, 'Aqua jog', '4 × 1 min · conditioning', 'Run in place or across the deep end with no bottom contact (or high-knee run in chest-deep water). Drive knees up, pump arms. Water resistance = great engine work with zero joint pounding.', 4, 60, 60, false, 2 from d
    union all
    select id, 'Pool jump squats', '3 × 12 · legs/power', 'Chest-deep water, sink into a squat and explode UP as high as you can, letting the water slow your landing. Builds jumping power with almost no impact on the knees.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Lateral bounds / shuffles', '3 × 30 sec · agility', 'Waist-to-chest deep, bound or shuffle side to side, pushing hard against the water. Trains the side-to-side dodge you use in dodgeball.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Pool-edge push-ups', '3 × 8–12 · push', 'Hands on the pool deck/edge, press your torso up out of the water like a push-up/dip, then lower under control. Hits chest, shoulders and triceps.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Flutter kicks on the wall', '3 × 30 sec · core/legs', 'Hold the edge, extend your body out behind you on the surface, and flutter kick from the hips. Keep your core tight so your hips don''t sink.', 3, 45, 90, false, 6 from d
    union all
    select id, 'Treading water', '3 × 45 sec · full-body', 'Deep end, stay afloat using sculling arm circles and an eggbeater/flutter kick. For a challenge, hold hands out of the water so your legs do all the work.', 3, 45, 90, false, 7 from d
    union all
    select id, 'Easy cool-down swim', '3–5 min · recovery', 'Slow laps or a relaxed float. Let your heart rate come down. Pool time doubles as the mood/stress reset.', 1, 60, 90, false, 8 from d;

  perform public.refresh_plan_estimates(v_plan);
end $$;

-- ---------- Upper/Lower — no barbells ------------------------------
do $$
declare v_plan uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility)
  values (null, true, 'gym', 'upper-lower-no-barbell', 'Upper/Lower — no barbells', 'Four-day upper/lower split built for gyms without barbells or racks: Smith machine, dumbbells and machines only.', 'template', 'public')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  -- Templates are regenerated wholesale; user plans are untouched.
  delete from days where plan_id = v_plan;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'UA', 'Upper A', 'Upper body — push + pull', 1)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Smith Machine Bench Press', '3 × 8–10 · chest', 'Set the bench so the bar lines up with your mid-chest. Twist to unrack, lower to your chest with elbows about 45°, press up. The fixed bar path makes this safe to push solo.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Lat Pulldown', '3 × 10–12 · back', 'Grip a bit wider than shoulders, chest tall, pull the bar to your collarbone by driving your elbows down toward your hips. Squeeze your back — don''t lean way back or yank with just the arms.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Dumbbell Shoulder Press', '3 × 10–12 · shoulders', 'Seated with back support. Press from ear height to overhead without clanging the dumbbells together. Keep your ribs down so your lower back doesn''t arch.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Seated Machine Row', '3 × 10–12 · back', 'Chest on the pad, pull the handles to your torso leading with your elbows, squeeze your shoulder blades together, then control the return. No jerking with the lower back.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Dumbbell Lateral Raise', '3 × 12–15 · shoulders', 'Slight bend in the elbows, raise the dumbbells out to the sides to shoulder height like pouring water, lead with the elbows. Light and smooth — this builds shoulder width.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Triceps Pushdown', '3 × 12–15 · arms', 'Cable/machine, elbows pinned to your sides, push down until your arms are straight, control back up. Only the forearms move. Superset with the curls below.', 3, 45, 90, false, 6 from d
    union all
    select id, 'Dumbbell Biceps Curl', '3 × 12–15 · arms', 'Elbows at your sides, curl without swinging your torso, squeeze at the top, lower slowly. Superset with pushdowns to save time.', 3, 45, 90, false, 7 from d
    union all
    select id, 'Optional: 12–15 min cardio', 'finisher · fat loss', 'Incline treadmill walk (try speed 3, incline 12), bike, or elliptical at moderate effort. Great for the fat-loss goal without hurting recovery.', 1, 45, 60, true, 8 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'LA', 'Lower A', 'Lower body — quad focus', 2)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Smith Machine Squat', '3 × 8–10 · legs', 'Bar on your traps (not your neck), feet slightly forward of the bar. Brace your core, sit down and back to at least parallel, drive up through mid-foot. The Smith lets you focus on depth without balancing a bar.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Leg Press', '3 × 10–12 · legs', 'Feet shoulder-width, mid-platform. Lower until knees are ~90° keeping your lower back flat on the pad, press through your heels, don''t slam the knees into a lock.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Seated Leg Curl', '3 × 10–12 · hamstrings', 'Pad just above your heels, curl down and squeeze your hamstrings hard, then control the weight back up slowly — don''t let it snap back.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Dumbbell Walking Lunges', '3 × 10/leg · legs', 'A dumbbell in each hand, step out, drop the back knee toward the floor, torso tall, push through the front heel to stand. No walking space? Do reverse lunges in place.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Calf Raise', '3 × 15 · calves', 'Balls of your feet on a step or the leg-press platform, rise up as high as you can, pause a beat at the top, lower slowly for a full stretch. Calves love the slow tempo.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Plank', '3 × 30–45 sec · core', 'Forearms down, body in one straight line — no sagging hips, no piked butt. Squeeze glutes and abs and breathe. Add time as it gets easier.', 3, 45, 90, false, 6 from d
    union all
    select id, 'Optional: 12–15 min cardio', 'finisher · fat loss', 'Keep it easy on leg day — bike or incline walk so you don''t fry your legs. Skip it if they''re toast; the lifting already did plenty.', 1, 45, 60, true, 7 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'UB', 'Upper B', 'Upper body — back + arms', 3)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Incline Dumbbell Press', '3 × 8–10 · chest', 'Bench at about 30°. Lower the dumbbells to your upper chest with elbows ~45°, press up and slightly together. Hits the upper chest for a fuller look.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Assisted Pull-Up', '3 × 8–10 · back', 'Use the assist machine — set enough help to get 8–10 clean reps, pull your chin over the bar, control down. No assist machine at your location? Do close-grip lat pulldowns instead.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Machine Chest Press', '3 × 10–12 · chest', 'Handles at mid-chest height, press out without locking hard, control back to a slight stretch. A safe way to push close to failure when you''re training solo.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Reverse Pec Deck', '3 × 12–15 · rear delts', 'Face the pad, arms out to the sides squeezing your shoulder blades, lead with the elbows. Bulletproofs your posture and shoulders. No machine? Bent-over dumbbell rear-delt raises.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Dumbbell Biceps Curl', '3 × 10–12 · arms', 'Elbows at your sides, curl without swinging, slow on the way down. Alternate arms or do both together.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Overhead Dumbbell Triceps Extension', '3 × 10–12 · arms', 'One dumbbell held overhead in both hands, lower it behind your head by bending the elbows, then extend back up. Keep your elbows pointing forward, not flaring out.', 3, 45, 90, false, 6 from d
    union all
    select id, 'Optional: 12–15 min cardio', 'finisher · fat loss', 'Incline walk, bike, or elliptical at a moderate pace. Or hit the stairs — anything that keeps you moving supports the lean-out.', 1, 45, 60, true, 7 from d;

  with d as (
    insert into days (plan_id, key, title, subtitle, sort)
    values (v_plan, 'LB', 'Lower B', 'Lower body — hamstring + glute focus', 4)    returning id
  )
  insert into exercises (day_id, name, scheme, cue, sets, work_seconds, rest_seconds, optional, sort)
    select id, 'Dumbbell Romanian Deadlift', '3 × 8–10 · hamstrings/glutes', 'Dumbbells in front of your thighs, soft knees, push your hips BACK (not down) like closing a car door with your butt. Let the dumbbells slide down your legs until you feel the hamstring stretch, then drive your hips forward to stand tall. Flat back the whole time.', 3, 45, 150, false, 1 from d
    union all
    select id, 'Leg Extension', '3 × 12–15 · quads', 'Pad resting on top of your shins, extend to straight, squeeze your quads at the top, lower under control. A safe, joint-friendly quad builder.', 3, 45, 150, false, 2 from d
    union all
    select id, 'Smith Machine Reverse Lunge', '3 × 10/leg · legs', 'Bar on your traps, step one foot back and drop that knee toward the floor, push through the front heel to return. Easier on the knees than forward lunges. Or do dumbbell Bulgarian split squats.', 3, 45, 90, false, 3 from d
    union all
    select id, 'Lying Leg Curl', '3 × 10–12 · hamstrings', 'If a lying curl is free, use it for a different angle than Lower A; otherwise repeat the seated curl. Curl and squeeze, control the return.', 3, 45, 90, false, 4 from d
    union all
    select id, 'Hip Abduction Machine', '3 × 15 · glutes', 'Push your knees outward against the pads, squeeze your glutes at the end, control back in. Builds the glutes and hip stability.', 3, 45, 90, false, 5 from d
    union all
    select id, 'Captain''s Chair Knee Raise', '3 × 12–15 · core', 'Forearms on the pads, back flat against the pad, raise your knees toward your chest using your abs — no swinging — then lower slowly. Or do decline-bench crunches.', 3, 45, 90, false, 6 from d
    union all
    select id, 'Optional: 12–15 min cardio', 'finisher · fat loss', 'Keep it light on leg day — an easy bike or incline walk. Steps outside the gym matter more here than smashing cardio right after leg work.', 1, 45, 60, true, 7 from d;

  perform public.refresh_plan_estimates(v_plan);
end $$;

-- ---------- Bowl Rotation — Asian & Latin ------------------------------
do $$
declare v_plan uuid; v_build uuid; v_prep uuid;
begin
  insert into plans (owner_id, is_template, kind, slug, name, description, source, visibility, tracking_mode)
  values (null, true, 'food', 'bowl-rotation-asian-latin', 'Bowl Rotation — Asian & Latin', 'Batch a few components twice a week, then assemble bowls in five minutes. Four rotating flavour profiles so nothing repeats, plus a designed four-minute fallback for days when nothing got prepped.', 'template', 'public', 'none')
  on conflict (slug) where is_template do update
    set name = excluded.name, description = excluded.description
  returning id into v_plan;

  delete from food_items    where plan_id = v_plan;
  delete from builds        where plan_id = v_plan;
  delete from prep_sessions where plan_id = v_plan;

  insert into food_items (plan_id, name, role, batch_cooked, shelf_life_days, sort) values
    (v_plan, 'Shredded chicken', 'protein', true, 4, 1),
    (v_plan, 'Ground beef', 'protein', true, 4, 2),
    (v_plan, 'Shrimp', 'protein', false, 2, 3),
    (v_plan, 'Hard-boiled eggs', 'protein', true, 7, 4),
    (v_plan, 'Rotisserie chicken', 'protein', false, 4, 5),
    (v_plan, 'Greek yogurt', 'protein', false, 14, 6),
    (v_plan, 'Jasmine rice', 'base', true, 5, 7),
    (v_plan, 'Rice noodles', 'base', false, 365, 8),
    (v_plan, 'Naan', 'base', false, 7, 9),
    (v_plan, 'Tortillas', 'base', false, 21, 10),
    (v_plan, 'Frozen stir-fry veg', 'veg', false, 365, 11),
    (v_plan, 'Peppers & onions, roasted', 'veg', true, 5, 12),
    (v_plan, 'Broccoli slaw', 'veg', false, 7, 13),
    (v_plan, 'Edamame', 'veg', false, 365, 14),
    (v_plan, 'Bagged salad', 'veg', false, 5, 15),
    (v_plan, 'Cucumber, herbs & lime', 'veg', false, 5, 16),
    (v_plan, 'Soy-ginger-garlic sauce', 'sauce', false, 30, 17),
    (v_plan, 'Peanut sauce', 'sauce', false, 30, 18),
    (v_plan, 'Gochujang sauce', 'sauce', false, 60, 19),
    (v_plan, 'Chipotle-lime sauce', 'sauce', false, 21, 20),
    (v_plan, 'Salsa verde', 'sauce', false, 14, 21),
    (v_plan, 'Tikka masala sauce (jar)', 'sauce', false, 365, 22),
    (v_plan, 'Pho-style broth', 'sauce', false, 5, 23),
    (v_plan, 'Chili crisp', 'extra', false, 365, 24),
    (v_plan, 'Cheese', 'extra', false, 21, 25);

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'A', 'Asian bowl', 'Rice, protein, veg, and whichever sauce you feel like.', false, 6, 1)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Jasmine rice', 1),
    ('Shredded chicken', 2),
    ('Frozen stir-fry veg', 3),
    ('Soy-ginger-garlic sauce', 4),
    ('Chili crisp', 5)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'B', 'Latin bowl', 'Burrito bowl shape. Swap rice for tortillas whenever.', false, 6, 2)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Jasmine rice', 1),
    ('Ground beef', 2),
    ('Peppers & onions, roasted', 3),
    ('Chipotle-lime sauce', 4),
    ('Cheese', 5)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'C', 'Tikka masala', 'Jarred sauce is genuinely good. Naan stays.', false, 15, 3)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Jasmine rice', 1),
    ('Shredded chicken', 2),
    ('Tikka masala sauce (jar)', 3),
    ('Naan', 4)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'D', 'Broth bowl', 'Pho/ramen shape — the highest-volume, most filling option.', false, 8, 4)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Rice noodles', 1),
    ('Pho-style broth', 2),
    ('Shrimp', 3),
    ('Cucumber, herbs & lime', 4),
    ('Broccoli slaw', 5)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'FALLBACK', 'The four-minute meal', 'Nothing prepped, no energy. This still counts as following the plan.', true, 4, 5)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Rotisserie chicken', 1),
    ('Bagged salad', 2),
    ('Jasmine rice', 3)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into builds (plan_id, key, title, subtitle, is_fallback, est_minutes, sort)
  values (v_plan, 'GRAB', 'Grab-and-go protein', 'For the front fridge shelf. Zero assembly, zero decisions.', true, 1, 6)
  returning id into v_build;
  insert into build_items (build_id, food_item_id, sort)
  select v_build, fi.id, x.sort from (values
    ('Greek yogurt', 1),
    ('Hard-boiled eggs', 2)
  ) as x(name, sort)
  join food_items fi on fi.plan_id = v_plan and fi.name = x.name;

  insert into prep_sessions (plan_id, key, title, weekday, est_minutes, sort)
  values (v_plan, 'sun', 'Sunday — the big one', 0, 50, 1)
  returning id into v_prep;
  insert into prep_tasks (prep_session_id, text, food_item_id, sort)
  select v_prep, x.text, fi.id, x.sort from (values
    ('Podcast on, oven to 425, big pot of water on', null, 1),
    ('Cook a batch of rice', 'Jasmine rice', 2),
    ('Cook and shred the chicken', 'Shredded chicken', 3),
    ('Roast a tray of peppers and onions', 'Peppers & onions, roasted', 4),
    ('Hard-boil a half dozen eggs', 'Hard-boiled eggs', 5),
    ('Portion into clear containers, front shelf of the fridge', null, 6)
  ) as x(text, item_name, sort)
  left join food_items fi on fi.plan_id = v_plan and fi.name = x.item_name;

  insert into prep_sessions (plan_id, key, title, weekday, est_minutes, sort)
  values (v_plan, 'wed', 'Wednesday — after the gym', 3, 35, 2)
  returning id into v_prep;
  insert into prep_tasks (prep_session_id, text, food_item_id, sort)
  select v_prep, x.text, fi.id, x.sort from (values
    ('Brown the ground beef', 'Ground beef', 1),
    ('Restock the grab-and-go shelf', null, 2),
    ('Chop cucumber, herbs and lime for the week', 'Cucumber, herbs & lime', 3),
    ('Anything from Sunday gone off? Bin it now, not Friday', null, 4)
  ) as x(text, item_name, sort)
  left join food_items fi on fi.plan_id = v_plan and fi.name = x.item_name;

end $$;

